spring:
  datasource:
    url: jdbc:h2:mem:bookdb
    #url: jdbc:postgresql://localhost:5432/music
    #username: postgres
    #password: postgres
    #hikari:
    #  schema: db

  jpa:
    hibernate:
      ddl-auto: none

  liquibase:
    enabled: true
    drop-first: true